from __future__ import annotations

import argparse
import re
from dataclasses import dataclass, field
from pathlib import Path


TABLE_START_RE = re.compile(r"^CREATE TABLE \[dbo\]\.\[(?P<table>[^\]]+)\]\($", re.IGNORECASE)
CREATE_END_RE = re.compile(r"^\)\s+ON\s+\[PRIMARY\](?:\s+TEXTIMAGE_ON\s+\[PRIMARY\])?$", re.IGNORECASE)
COLUMN_RE = re.compile(
    r"^\s*\[(?P<name>[^\]]+)\]\s+\[(?P<type>[^\]]+)\]"
    r"(?:\((?P<args>[^)]+)\))?"
    r"(?P<identity>\s+IDENTITY\(\d+,\d+\))?"
    r"\s+(?P<nullable>NOT NULL|NULL),?$",
    re.IGNORECASE,
)
CONSTRAINT_RE = re.compile(
    r"CONSTRAINT \[(?P<name>[^\]]+)\]\s+(?P<kind>PRIMARY KEY|UNIQUE)",
    re.IGNORECASE,
)
CONSTRAINT_COLUMN_RE = re.compile(r"\[(?P<column>[^\]]+)\]\s+(?:ASC|DESC)", re.IGNORECASE)
DEFAULT_RE = re.compile(
    r"ALTER TABLE \[dbo\]\.\[(?P<table>[^\]]+)\]\s+ADD\s+CONSTRAINT \[(?P<name>[^\]]+)\]\s+"
    r"DEFAULT\s+\((?P<expr>.+?)\)\s+FOR\s+\[(?P<column>[^\]]+)\]$",
    re.IGNORECASE,
)
FK_RE = re.compile(
    r"ALTER TABLE \[dbo\]\.\[(?P<table>[^\]]+)\]\s+WITH\s+(?:NO)?CHECK\s+ADD\s+CONSTRAINT "
    r"\[(?P<name>[^\]]+)\]\s+FOREIGN KEY\(\[(?P<column>[^\]]+)\]\)\s*"
    r"REFERENCES \[dbo\]\.\[(?P<ref_table>[^\]]+)\]\s+\(\[(?P<ref_column>[^\]]+)\]\)",
    re.IGNORECASE | re.MULTILINE | re.DOTALL,
)


@dataclass(slots=True)
class Column:
    name: str
    sqlserver_type: str
    type_args: str | None
    nullable: bool
    identity: bool
    default: str | None = None

    def postgres_type(self) -> str:
        base = self.sqlserver_type.lower()
        args = self.type_args

        if self.identity:
            if base == "smallint":
                return "smallint GENERATED BY DEFAULT AS IDENTITY"
            if base == "tinyint":
                return "smallint GENERATED BY DEFAULT AS IDENTITY"
            return "integer GENERATED BY DEFAULT AS IDENTITY"

        if base == "int":
            return "integer"
        if base == "smallint":
            return "smallint"
        if base == "tinyint":
            return "smallint"
        if base == "bit":
            return "boolean"
        if base in {"datetime", "smalldatetime"}:
            return "timestamp without time zone"
        if base in {"text", "ntext"}:
            return "text"
        if base == "image":
            return "bytea"
        if base in {"char", "varchar", "nvarchar"}:
            if not args:
                return "text"
            return f"varchar({args})"
        if base in {"numeric", "decimal"}:
            return f"{base}({args})" if args else base
        if base == "float":
            return "double precision"
        if base == "real":
            return "real"
        if base in {"binary", "varbinary"}:
            return "bytea"

        raise ValueError(f"Tipo SQL Server nao mapeado: {self.sqlserver_type}")

    def postgres_default(self) -> str | None:
        if self.default is None:
            return None

        expr = self.default.strip()
        while expr.startswith("(") and expr.endswith(")"):
            inner = expr[1:-1].strip()
            if inner.count("(") != inner.count(")"):
                break
            expr = inner

        if expr.lower() == "getdate()":
            return "CURRENT_TIMESTAMP"

        if self.sqlserver_type.lower() == "bit":
            if expr == "0":
                return "FALSE"
            if expr == "1":
                return "TRUE"

        if self.sqlserver_type.lower() in {"char", "varchar", "nvarchar", "text", "ntext"}:
            if re.fullmatch(r"-?\d+", expr):
                return f"'{expr}'"

        if expr.startswith("N'"):
            return expr[1:]

        return expr


@dataclass(slots=True)
class TableConstraint:
    name: str
    kind: str
    columns: list[str]


@dataclass(slots=True)
class ForeignKey:
    name: str
    table: str
    column: str
    ref_table: str
    ref_column: str


@dataclass(slots=True)
class Table:
    name: str
    columns: list[Column] = field(default_factory=list)
    constraints: list[TableConstraint] = field(default_factory=list)

    def column_map(self) -> dict[str, Column]:
        return {column.name: column for column in self.columns}


def parse_tables(text: str) -> list[Table]:
    lines = text.splitlines()
    tables: list[Table] = []
    current_table: Table | None = None
    block_lines: list[str] = []

    for line in lines:
        if current_table is None:
            start = TABLE_START_RE.match(line.strip())
            if start:
                current_table = Table(name=start.group("table"))
                block_lines = []
            continue

        if CREATE_END_RE.match(line.strip()):
            parse_table_block(current_table, block_lines)
            tables.append(current_table)
            current_table = None
            block_lines = []
            continue

        block_lines.append(line)

    return tables


def parse_table_block(table: Table, block_lines: list[str]) -> None:
    constraint_buffer: list[str] | None = None

    for raw_line in block_lines:
        line = raw_line.rstrip()
        stripped = line.strip()
        if not stripped:
            continue

        if constraint_buffer is not None:
            constraint_buffer.append(stripped)
            if stripped.startswith(")WITH") or stripped.startswith(") ON") or stripped == ")":
                parse_constraint(table, " ".join(constraint_buffer))
                constraint_buffer = None
            continue

        if stripped.startswith("CONSTRAINT "):
            constraint_buffer = [stripped]
            if stripped.endswith(")"):
                parse_constraint(table, " ".join(constraint_buffer))
                constraint_buffer = None
            continue

        if stripped.startswith("["):
            match = COLUMN_RE.match(stripped)
            if not match:
                raise ValueError(f"Linha de coluna nao reconhecida em {table.name}: {stripped}")
            table.columns.append(
                Column(
                    name=match.group("name"),
                    sqlserver_type=match.group("type"),
                    type_args=match.group("args"),
                    nullable=match.group("nullable").upper() == "NULL",
                    identity=bool(match.group("identity")),
                )
            )


def parse_constraint(table: Table, text: str) -> None:
    match = CONSTRAINT_RE.search(text)
    if not match:
        return

    columns = [item.group("column") for item in CONSTRAINT_COLUMN_RE.finditer(text)]
    table.constraints.append(
        TableConstraint(
            name=match.group("name"),
            kind=match.group("kind").upper(),
            columns=columns,
        )
    )


def apply_defaults(text: str, tables: list[Table]) -> None:
    table_map = {table.name: table for table in tables}

    for line in text.splitlines():
        match = DEFAULT_RE.match(line.strip())
        if not match:
            continue

        table = table_map.get(match.group("table"))
        if table is None:
            continue

        column = table.column_map().get(match.group("column"))
        if column is None:
            continue

        column.default = match.group("expr")


def parse_foreign_keys(text: str) -> list[ForeignKey]:
    foreign_keys: list[ForeignKey] = []
    for match in FK_RE.finditer(text):
        foreign_keys.append(
            ForeignKey(
                name=match.group("name"),
                table=match.group("table"),
                column=match.group("column"),
                ref_table=match.group("ref_table"),
                ref_column=match.group("ref_column"),
            )
        )
    return foreign_keys


def quote_ident(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def render_table(table: Table) -> str:
    lines: list[str] = [f"CREATE TABLE {quote_ident(table.name)} ("]
    body: list[str] = []

    for column in table.columns:
        parts = [f"    {quote_ident(column.name)} {column.postgres_type()}"]
        default = column.postgres_default()
        if default is not None:
            parts.append(f"DEFAULT {default}")
        parts.append("NULL" if column.nullable else "NOT NULL")
        body.append(" ".join(parts))

    for constraint in table.constraints:
        if not constraint.columns:
            continue
        columns_sql = ", ".join(quote_ident(column) for column in constraint.columns)
        if constraint.kind == "PRIMARY KEY":
            body.append(
                f"    CONSTRAINT {quote_ident(constraint.name)} PRIMARY KEY ({columns_sql})"
            )
        elif constraint.kind == "UNIQUE":
            body.append(
                f"    CONSTRAINT {quote_ident(constraint.name)} UNIQUE ({columns_sql})"
            )

    lines.append(",\n".join(body))
    lines.append(");")
    return "\n".join(lines)


def render_foreign_key(foreign_key: ForeignKey) -> str:
    return (
        f"ALTER TABLE {quote_ident(foreign_key.table)} "
        f"ADD CONSTRAINT {quote_ident(foreign_key.name)} "
        f"FOREIGN KEY ({quote_ident(foreign_key.column)}) "
        f"REFERENCES {quote_ident(foreign_key.ref_table)} ({quote_ident(foreign_key.ref_column)});"
    )


def build_output(tables: list[Table], foreign_keys: list[ForeignKey]) -> str:
    chunks = [
        "-- Gerado automaticamente a partir de schemas.sql",
        "-- Ajustes aplicados para PostgreSQL:",
        "-- char/nvarchar -> varchar",
        "-- text/ntext -> text",
        "-- image -> bytea",
        "-- bit -> boolean",
        "-- datetime/smalldatetime -> timestamp without time zone",
        "-- IDENTITY -> GENERATED BY DEFAULT AS IDENTITY",
        "",
    ]

    for table in tables:
        chunks.append(render_table(table))
        chunks.append("")

    if foreign_keys:
        chunks.append("-- Chaves estrangeiras")
        for foreign_key in foreign_keys:
            chunks.append(render_foreign_key(foreign_key))
        chunks.append("")

    return "\n".join(chunks).rstrip() + "\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Converte um dump de schema do SQL Server para um schema inicial de PostgreSQL."
    )
    parser.add_argument(
        "--input",
        default="schemas.sql",
        help="Arquivo de entrada com o schema do SQL Server.",
    )
    parser.add_argument(
        "--output",
        default="schema_pg.sql",
        help="Arquivo de saida com o schema convertido para PostgreSQL.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    source_path = Path(args.input)
    output_path = Path(args.output)

    text = source_path.read_text(encoding="utf-8")
    tables = parse_tables(text)
    apply_defaults(text, tables)
    foreign_keys = parse_foreign_keys(text)

    output = build_output(tables, foreign_keys)
    output_path.write_text(output, encoding="utf-8")

    print(
        f"Gerado {output_path} com {len(tables)} tabelas e {len(foreign_keys)} chaves estrangeiras."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
