-- Gerado automaticamente a partir de schemas.sql
-- Ajustes aplicados para PostgreSQL:
-- char/nvarchar -> varchar
-- text/ntext -> text
-- image -> bytea
-- bit -> boolean
-- datetime/smalldatetime -> timestamp without time zone
-- IDENTITY -> GENERATED BY DEFAULT AS IDENTITY

CREATE TABLE "assunto_tipo" (
    "tpa_cd" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "tpa_cla_cd" smallint NOT NULL,
    "tpa_ds" varchar(40) NOT NULL,
    "tpa_st" smallint DEFAULT 0 NOT NULL,
    CONSTRAINT "PK_assunto_tipo" PRIMARY KEY ("tpa_cd")
);

CREATE TABLE "assunto_denuncia" (
    "ass_cd" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "ass_den_cd" integer NOT NULL,
    "ass_cla_cd" smallint NOT NULL,
    "ass_tpa_cd" smallint NOT NULL,
    "ass_principal" smallint DEFAULT 0 NOT NULL,
    CONSTRAINT "PK_denuncia_assuntos" PRIMARY KEY ("ass_cd")
);

CREATE TABLE "assunto_classe" (
    "cla_cd" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "cla_ds" varchar(40) NOT NULL,
    "cla_st" smallint DEFAULT 0 NOT NULL,
    CONSTRAINT "PK_assunto_classe" PRIMARY KEY ("cla_cd"),
    CONSTRAINT "IX_assunto_classe" UNIQUE ("cla_ds")
);

CREATE TABLE "xpto_denuncia" (
    "dxp_cd" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "dxp_xpt_cd" smallint NOT NULL,
    "dxp_den_cd" integer NOT NULL,
    "dxp_data" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "dxp_usu_cd" smallint NOT NULL,
    CONSTRAINT "PK_xpto_denuncia" PRIMARY KEY ("dxp_cd")
);

CREATE TABLE "veiculos" (
    "vei_cd" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "den_cd" integer NOT NULL,
    "marca" smallint DEFAULT 0 NOT NULL,
    "modelo" smallint DEFAULT 0 NOT NULL,
    "cor" varchar(15) DEFAULT '' NOT NULL,
    "ano_mod" smallint DEFAULT 0 NOT NULL,
    "ano_fab" smallint DEFAULT 0 NOT NULL,
    "placa" varchar(7) DEFAULT '' NOT NULL,
    "municipio" varchar(30) DEFAULT '' NOT NULL,
    "uf" varchar(2) DEFAULT '' NOT NULL,
    "chassis" varchar(20) DEFAULT '0' NOT NULL,
    "proprietario" varchar(50) DEFAULT '' NOT NULL,
    "com_nome" varchar(50) DEFAULT '' NOT NULL,
    "com_endereco" varchar(60) DEFAULT '' NOT NULL,
    "com_bairro" varchar(30) DEFAULT '' NOT NULL,
    "com_municipio" varchar(30) DEFAULT '' NOT NULL,
    "com_uf" varchar(2) DEFAULT '' NOT NULL,
    "com_telefone" varchar(40) DEFAULT '' NOT NULL,
    "com_doc" varchar(30) DEFAULT '' NOT NULL,
    "com_tipo" smallint DEFAULT 0 NOT NULL,
    "ro_dp" varchar(20) DEFAULT '' NOT NULL,
    "seguradora" varchar(30) DEFAULT '' NOT NULL,
    "detalhes" text DEFAULT '' NOT NULL,
    CONSTRAINT "PK_veiculos" PRIMARY KEY ("vei_cd")
);

CREATE TABLE "numeracao" (
    "numero" integer NOT NULL,
    "dataalt" timestamp without time zone NOT NULL
);

CREATE TABLE "log_alteracoes" (
    "log_cd" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "den_cd" integer NULL,
    "operacao" varchar(10) NULL,
    "data" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "usu_cd" smallint NULL,
    "versao" smallint NULL,
    "original" text NULL,
    "novo" text NULL
);

CREATE TABLE "vei_marca" (
    "mar_cd" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "mar_ds" varchar(30) NOT NULL,
    CONSTRAINT "PK_vei_marca" PRIMARY KEY ("mar_cd"),
    CONSTRAINT "IX_vei_marca" UNIQUE ("mar_ds")
);

CREATE TABLE "usuarios_tipos" (
    "utp_cd" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "utp_ds" varchar(20) NOT NULL,
    CONSTRAINT "PK_usuarios_tipos" PRIMARY KEY ("utp_cd"),
    CONSTRAINT "IX_usuarios_tipos" UNIQUE ("utp_ds")
);

CREATE TABLE "usuarios" (
    "usu_cd" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "usu_nome" varchar(50) NOT NULL,
    "usu_login" varchar(12) NOT NULL,
    "usu_turno" varchar(10) NOT NULL,
    "usu_tipo" smallint NOT NULL,
    "usu_senha" varchar(8) NOT NULL,
    "usu_status" smallint DEFAULT 0 NOT NULL,
    CONSTRAINT "PK_usuarios" PRIMARY KEY ("usu_cd"),
    CONSTRAINT "IX_usuarios" UNIQUE ("usu_login")
);

CREATE TABLE "unidades_metricas" (
    "umt_cd" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "umt_ds" varchar(40) NOT NULL,
    CONSTRAINT "PK_unidades_metricas" PRIMARY KEY ("umt_cd"),
    CONSTRAINT "IX_unidades_metricas" UNIQUE ("umt_ds")
);

CREATE TABLE "rotinas" (
    "rot_cd" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "rot_ds" varchar(30) NOT NULL,
    "rot_nomesis" varchar(30) NOT NULL,
    "rot_st" smallint DEFAULT 0 NOT NULL,
    "rot_default_adm" smallint DEFAULT 0 NOT NULL,
    "rot_default_sup" smallint DEFAULT 0 NOT NULL,
    "rot_default_ana" smallint DEFAULT 0 NOT NULL,
    "rot_default_ate" smallint DEFAULT 0 NOT NULL,
    "ordem" smallint DEFAULT 0 NOT NULL,
    CONSTRAINT "PK_rotinas" PRIMARY KEY ("rot_cd")
);

CREATE TABLE "resultado_tipo" (
    "rtp_cd" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "rtp_ds" varchar(50) NOT NULL,
    "rtp_st" smallint DEFAULT 0 NOT NULL,
    CONSTRAINT "PK_resultado_tipo" PRIMARY KEY ("rtp_cd"),
    CONSTRAINT "IX_resultado_tipo" UNIQUE ("rtp_ds")
);

CREATE TABLE "resultado_indireto" (
    "rei_cd" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "rei_den_cd" integer NOT NULL,
    "rei_cad_data" timestamp without time zone NOT NULL,
    "rei_usu_cd" smallint NOT NULL,
    CONSTRAINT "PK_resultado_indireto" PRIMARY KEY ("rei_cd")
);

CREATE TABLE "resultado_direto" (
    "red_cd" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "red_den_cd" integer NOT NULL,
    "red_rtp_cd" smallint NOT NULL,
    "red_resp_data" timestamp without time zone NULL,
    "red_oper_data" timestamp without time zone NULL,
    "red_cad_data" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "red_usu_cd" smallint NOT NULL,
    "red_relato" text NOT NULL,
    "red_ext_cd" integer DEFAULT 0 NOT NULL,
    "red_oet_cd" integer DEFAULT 0 NOT NULL,
    CONSTRAINT "PK_resultado_direto" PRIMARY KEY ("red_cd")
);

CREATE TABLE "relatorios" (
    "rel_cd" smallint NOT NULL,
    "rel_descricao" varchar(50) NOT NULL,
    "rel_file" varchar(30) NOT NULL,
    "rel_form" varchar(20) NOT NULL,
    "rel_sql" text NOT NULL,
    "rel_filtros" varchar(50) NOT NULL,
    "rel_ordem" smallint NOT NULL,
    "rel_grafico" bytea NULL,
    "rel_tipo" varchar(1) NOT NULL,
    "rel_graf_itens" smallint NOT NULL
);

CREATE TABLE "quantifica_resultado" (
    "qtf_cd" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "qtf_den_cd" integer NOT NULL,
    "qtf_cli_cd" smallint NOT NULL,
    "qtf_tpi_cd" smallint NOT NULL,
    "qtf_itm_cd" smallint NOT NULL,
    "qtf_qtd" integer NOT NULL,
    "qtf_data" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "qtf_usu_cd" smallint NOT NULL,
    CONSTRAINT "PK_quantifica_resultado" PRIMARY KEY ("qtf_cd")
);

CREATE TABLE "orgaos_internos" (
    "int_cd" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "int_ds" varchar(50) NOT NULL,
    "int_st" smallint DEFAULT 0 NOT NULL,
    "int_dest" varchar(80) DEFAULT '' NOT NULL,
    CONSTRAINT "PK_orgaos_internos" PRIMARY KEY ("int_cd"),
    CONSTRAINT "IX_orgaos_internos" UNIQUE ("int_ds")
);

CREATE TABLE "orgaos_externos_tipos" (
    "oet_cd" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "oet_ds" varchar(40) NOT NULL,
    "oet_st" smallint DEFAULT 0 NOT NULL,
    CONSTRAINT "PK_orgaos_externos_tipos" PRIMARY KEY ("oet_cd"),
    CONSTRAINT "IX_orgaos_externos_tipos" UNIQUE ("oet_ds")
);

CREATE TABLE "chaves" (
    "denuncia" integer NOT NULL,
    "atendimento" integer NOT NULL
);

CREATE TABLE "buscas" (
    "bus_cd" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "bus_ds" varchar(100) NOT NULL,
    "bus_buscas" text NOT NULL,
    "bus_usu_cd" integer DEFAULT 0 NOT NULL,
    "bus_rel_cd" integer DEFAULT 0 NOT NULL,
    CONSTRAINT "PK_buscas" PRIMARY KEY ("bus_cd")
);

CREATE TABLE "aux_uf" (
    "udf_cd" varchar(2) NOT NULL,
    "udf_ds" varchar(20) NOT NULL,
    CONSTRAINT "PK_aux_uf" PRIMARY KEY ("udf_cd")
);

CREATE TABLE "aux_subbairro" (
    "sba_cd" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "sba_bai_ds" varchar(40) NOT NULL,
    "sba_ds" varchar(40) NOT NULL,
    CONSTRAINT "PK_aux_subbairro" PRIMARY KEY ("sba_cd")
);

CREATE TABLE "aux_porte" (
    "prt_cd" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "prt_ds" varchar(10) NOT NULL,
    CONSTRAINT "PK_aux_porte" PRIMARY KEY ("prt_cd"),
    CONSTRAINT "IX_aux_porte" UNIQUE ("prt_ds")
);

CREATE TABLE "aux_pele" (
    "pel_cd" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "pel_ds" varchar(10) NOT NULL,
    CONSTRAINT "PK_aux_pele" PRIMARY KEY ("pel_cd"),
    CONSTRAINT "IX_aux_pele" UNIQUE ("pel_ds")
);

CREATE TABLE "aux_olhos" (
    "olh_cd" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "olh_ds" varchar(10) NOT NULL,
    CONSTRAINT "PK_aux_olhos" PRIMARY KEY ("olh_cd"),
    CONSTRAINT "IX_aux_olhos" UNIQUE ("olh_ds")
);

CREATE TABLE "aux_municipio" (
    "mun_cd" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "mun_ds" varchar(40) NOT NULL,
    "mun_uf_cd" varchar(2) NOT NULL,
    CONSTRAINT "PK_aux_municipios" PRIMARY KEY ("mun_cd")
);

CREATE TABLE "aux_logradouro" (
    "lgr_cd" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "lgr_tp" varchar(10) DEFAULT '' NOT NULL,
    "lgr_ds" varchar(60) DEFAULT '' NOT NULL,
    "lgr_bai_ds" varchar(40) DEFAULT '' NOT NULL,
    "lgr_sba_ds" varchar(40) DEFAULT '' NOT NULL,
    "lgr_mun_ds" varchar(40) DEFAULT '' NOT NULL,
    "lgr_uf_cd" varchar(2) DEFAULT '' NOT NULL,
    "lgr_cep" integer DEFAULT 0 NOT NULL,
    CONSTRAINT "PK_aux_logradouro" PRIMARY KEY ("lgr_cd")
);

CREATE TABLE "aux_faixa_etaria" (
    "fet_cd" varchar(10) NOT NULL,
    "fet_ds" varchar(15) NOT NULL,
    CONSTRAINT "PK_aux_faixa_etaria" PRIMARY KEY ("fet_cd"),
    CONSTRAINT "IX_aux_faixa_etaria" UNIQUE ("fet_ds")
);

CREATE TABLE "aux_estatura" (
    "est_cd" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "est_ds" varchar(10) NOT NULL,
    CONSTRAINT "PK_aux_estatura" PRIMARY KEY ("est_cd"),
    CONSTRAINT "IX_aux_estatura" UNIQUE ("est_ds")
);

CREATE TABLE "aux_cabelo" (
    "cab_cd" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "cab_ds" varchar(10) NOT NULL,
    CONSTRAINT "PK_aux_cabelo" PRIMARY KEY ("cab_cd"),
    CONSTRAINT "IX_aux_cabelo" UNIQUE ("cab_ds")
);

CREATE TABLE "aux_bairro" (
    "bai_cd" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "bai_ds" varchar(40) DEFAULT '' NOT NULL,
    "bai_mun_ds" varchar(40) DEFAULT '' NOT NULL,
    "bai_uf_cd" varchar(2) DEFAULT '' NOT NULL,
    CONSTRAINT "PK_aux_bairro" PRIMARY KEY ("bai_cd")
);

CREATE TABLE "atendimento_tipo" (
    "att_cd" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "att_ds" varchar(40) NULL,
    "att_st" smallint DEFAULT 0 NULL,
    CONSTRAINT "PK_atendimento_tipo" PRIMARY KEY ("att_cd"),
    CONSTRAINT "IX_atendimento_tipo" UNIQUE ("att_ds")
);

CREATE TABLE "atendimento" (
    "atd_cd" integer DEFAULT 0 NOT NULL,
    "atd_dt_rec" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NULL,
    "atd_usu_cd" smallint DEFAULT 0 NULL,
    "atd_att_cd" smallint DEFAULT 0 NULL,
    "atd_texto" text DEFAULT '' NULL,
    "atd_den_cd" integer DEFAULT 0 NULL,
    "atd_den_num" varchar(15) DEFAULT '' NULL,
    CONSTRAINT "PK_atendimento" PRIMARY KEY ("atd_cd")
);

CREATE TABLE "acesso_tempo" (
    "usu_cd" smallint NOT NULL,
    "den_cd" integer NOT NULL,
    "atd_cd" integer NOT NULL,
    "locktime" timestamp without time zone NOT NULL,
    "unlocktime" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "l_status" varchar(1) NOT NULL,
    "u_status" varchar(1) NOT NULL
);

CREATE TABLE "acesso" (
    "ace_cd" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "ace_usu_cd" smallint NOT NULL,
    "ace_rot_cd" smallint NOT NULL,
    CONSTRAINT "PK_acesso" PRIMARY KEY ("ace_cd")
);

CREATE TABLE "item_tipo" (
    "tpi_cd" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "tpi_cli_cd" smallint NOT NULL,
    "tpi_ds" varchar(40) NOT NULL,
    "tpi_st" smallint DEFAULT 0 NOT NULL,
    CONSTRAINT "PK_item_tipo" PRIMARY KEY ("tpi_cd"),
    CONSTRAINT "IX_item_tipo" UNIQUE ("tpi_cli_cd", "tpi_ds")
);

CREATE TABLE "item_classe" (
    "cli_cd" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "cli_ds" varchar(40) NOT NULL,
    "cli_st" smallint DEFAULT 0 NOT NULL,
    CONSTRAINT "PK_item_classe" PRIMARY KEY ("cli_cd")
);

CREATE TABLE "item" (
    "itm_cd" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "itm_ds" varchar(40) NOT NULL,
    "itm_tpi_cd" smallint NOT NULL,
    "itm_umt_cd" smallint NOT NULL,
    "itm_st" smallint DEFAULT 0 NOT NULL,
    CONSTRAINT "PK_item" PRIMARY KEY ("itm_cd")
);

CREATE TABLE "graficos" (
    "grf_cd" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "descricao" varchar(50) NOT NULL,
    "codigo" varchar(30) NOT NULL,
    "grafico" bytea NOT NULL,
    CONSTRAINT "PK_graficos" PRIMARY KEY ("grf_cd")
);

CREATE TABLE "envolvidos" (
    "env_cd" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "env_den_cd" integer NOT NULL,
    "env_usu_cd" smallint NOT NULL,
    "env_nome" varchar(40) DEFAULT '' NOT NULL,
    "env_vulgo" varchar(30) DEFAULT '' NOT NULL,
    "env_end_tp" smallint DEFAULT 0 NOT NULL,
    "env_logr_tp" varchar(10) DEFAULT '' NOT NULL,
    "env_logr_ds" varchar(50) DEFAULT '' NOT NULL,
    "env_logr_num" varchar(10) DEFAULT '' NOT NULL,
    "env_logr_cmpl" varchar(20) DEFAULT '' NOT NULL,
    "env_logr_bairro" varchar(40) DEFAULT '' NOT NULL,
    "env_logr_subbairro" varchar(40) DEFAULT '' NOT NULL,
    "env_logr_mun" varchar(40) DEFAULT '' NOT NULL,
    "env_logr_uf" varchar(2) DEFAULT '' NOT NULL,
    "env_loc_ref" text DEFAULT '' NOT NULL,
    "env_sexo" varchar(1) DEFAULT '' NOT NULL,
    "env_idade" smallint DEFAULT 0 NOT NULL,
    "env_pele" smallint DEFAULT 0 NOT NULL,
    "env_estatura" smallint DEFAULT 0 NOT NULL,
    "env_olhos" smallint DEFAULT 0 NOT NULL,
    "env_cabelo" smallint DEFAULT 0 NOT NULL,
    "env_porte" smallint DEFAULT 0 NOT NULL,
    "env_caract" text DEFAULT '' NOT NULL,
    CONSTRAINT "PK_envolvidos" PRIMARY KEY ("env_cd")
);

CREATE TABLE "difusao_tipo" (
    "dit_cd" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "dit_ds" varchar(30) NOT NULL,
    "dit_st" smallint DEFAULT 0 NOT NULL,
    CONSTRAINT "PK_difusao_tipo" PRIMARY KEY ("dit_cd"),
    CONSTRAINT "IX_difusao_tipo" UNIQUE ("dit_ds")
);

CREATE TABLE "difusao_interna" (
    "din_cd" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "din_den_cd" integer NOT NULL,
    "din_int_cd" smallint NOT NULL,
    "din_data" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "din_dit_cd" smallint NOT NULL,
    "din_usu_cd" smallint NOT NULL,
    CONSTRAINT "PK_difusao_interna" PRIMARY KEY ("din_cd")
);

CREATE TABLE "dd_mulher" (
    "mul_cd" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "mul_den_cd" integer NOT NULL,
    "mul_lugar" varchar(50) DEFAULT '' NOT NULL,
    "mul_vive" varchar(50) DEFAULT '' NOT NULL,
    "mul_filhos" varchar(20) DEFAULT '' NOT NULL,
    "mul_filhos_qtd" smallint DEFAULT 0 NOT NULL,
    "mul_filhos_agd" varchar(20) DEFAULT '' NOT NULL,
    "mul_agr_alcool" varchar(20) DEFAULT '' NOT NULL,
    "mul_quando" varchar(40) DEFAULT '' NOT NULL,
    "mul_freq" varchar(40) DEFAULT '' NOT NULL,
    "mul_hora" varchar(20) DEFAULT '' NOT NULL,
    "mul_test" varchar(20) DEFAULT '' NOT NULL,
    "mul_t_pai_vit" boolean DEFAULT FALSE NOT NULL,
    "mul_t_mae_vit" boolean DEFAULT FALSE NOT NULL,
    "mul_t_pai_agr" boolean DEFAULT FALSE NOT NULL,
    "mul_t_mae_agr" boolean DEFAULT FALSE NOT NULL,
    "mul_t_filhos" boolean DEFAULT FALSE NOT NULL,
    "mul_t_outros" boolean DEFAULT FALSE NOT NULL,
    "mul_t_ods" varchar(50) DEFAULT '' NOT NULL,
    "mul_data" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "mul_tpag_fisica" boolean DEFAULT FALSE NOT NULL,
    "mul_tpag_verbal" boolean DEFAULT FALSE NOT NULL,
    "mul_tpag_sexual" boolean DEFAULT FALSE NOT NULL,
    "mul_tpag_carcere" boolean DEFAULT FALSE NOT NULL,
    "mul_tpag_ameaca" boolean DEFAULT FALSE NOT NULL,
    "mul_tpag_ninform" boolean DEFAULT FALSE NOT NULL,
    "mul_tpag_outros" boolean DEFAULT FALSE NOT NULL,
    "mul_tpag_ods" varchar(50) DEFAULT '' NOT NULL,
    "mul_agr_ab" boolean DEFAULT FALSE NOT NULL,
    "mul_agr_af" boolean DEFAULT FALSE NOT NULL,
    "mul_agr_pau" boolean DEFAULT FALSE NOT NULL,
    "mul_agr_fio" boolean DEFAULT FALSE NOT NULL,
    "mul_agr_cig" boolean DEFAULT FALSE NOT NULL,
    "mul_agr_mao" boolean DEFAULT FALSE NOT NULL,
    "mul_agr_est" boolean DEFAULT FALSE NOT NULL,
    "mul_agr_soc" boolean DEFAULT FALSE NOT NULL,
    "mul_agr_emp" boolean DEFAULT FALSE NOT NULL,
    "mul_agr_chu" boolean DEFAULT FALSE NOT NULL,
    "mul_agr_out" boolean DEFAULT FALSE NOT NULL,
    "mul_agr_ods" varchar(50) DEFAULT '' NOT NULL,
    CONSTRAINT "PK_dd_muher" PRIMARY KEY ("mul_den_cd")
);

CREATE TABLE "correlatas" (
    "cor_cd" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "cor_orig_den_cd" integer NOT NULL,
    "cor_ref_den_cd" integer NOT NULL,
    CONSTRAINT "PK_correlatas" PRIMARY KEY ("cor_cd")
);

CREATE TABLE "config" (
    "cfg_cd" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "cfg_uf" varchar(2) NOT NULL,
    "cfg_mun" varchar(40) NOT NULL,
    "cfg_capital" varchar(40) NOT NULL,
    "cfg_titulo" varchar(100) DEFAULT '' NOT NULL,
    CONSTRAINT "PK_config" PRIMARY KEY ("cfg_cd")
);

CREATE TABLE "denuncia_com" (
    "com_cd" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "den_cd" integer NOT NULL,
    "den_com" text NOT NULL,
    CONSTRAINT "PK_denuncia_com" PRIMARY KEY ("den_cd")
);

CREATE TABLE "denuncia" (
    "den_cd" integer DEFAULT 0 NOT NULL,
    "den_numero" integer DEFAULT 0 NOT NULL,
    "den_dt_rec" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "den_dt_alt" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "den_op_rec" smallint NOT NULL,
    "den_logr_manual" smallint DEFAULT 0 NOT NULL,
    "den_logr_tp" varchar(10) DEFAULT '' NOT NULL,
    "den_logr_ds" varchar(50) DEFAULT '' NOT NULL,
    "den_logr_num" varchar(10) DEFAULT '' NOT NULL,
    "den_logr_cmpl" varchar(20) DEFAULT '' NOT NULL,
    "den_logr_bairro" varchar(40) DEFAULT '' NOT NULL,
    "den_logr_subbairro" varchar(40) DEFAULT '' NOT NULL,
    "den_logr_mun" varchar(40) DEFAULT '' NOT NULL,
    "den_logr_uf" varchar(2) DEFAULT '' NOT NULL,
    "den_logr_cep" integer DEFAULT 0 NOT NULL,
    "den_loc_ref" text DEFAULT '' NOT NULL,
    "den_xpto" smallint DEFAULT 0 NOT NULL,
    "den_class" smallint DEFAULT 0 NOT NULL,
    "den_texto" text DEFAULT '' NOT NULL,
    "den_versao" smallint DEFAULT 0 NOT NULL,
    "den_corr_cd" integer DEFAULT 0 NOT NULL,
    "den_imediata" smallint DEFAULT 0 NOT NULL,
    "den_usu_lock" varchar(12) DEFAULT '' NOT NULL,
    "den_redifundir" boolean DEFAULT FALSE NOT NULL,
    CONSTRAINT "PK_denuncia" PRIMARY KEY ("den_cd")
);

CREATE TABLE "orgaos_externos" (
    "ext_cd" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "ext_ds" varchar(50) NOT NULL,
    "ext_oet_cd" smallint NOT NULL,
    "ext_st" smallint DEFAULT 0 NOT NULL,
    "ext_dest" varchar(80) DEFAULT '' NOT NULL,
    "ext_endereco" varchar(50) DEFAULT '' NOT NULL,
    "ext_bairro" varchar(40) DEFAULT '' NOT NULL,
    "ext_municipio" varchar(40) DEFAULT '' NOT NULL,
    "ext_uf" varchar(2) DEFAULT '' NOT NULL,
    "ext_cep" integer DEFAULT 0 NOT NULL,
    "ext_telefones" varchar(50) DEFAULT '' NOT NULL,
    CONSTRAINT "PK_orgaos_externos" PRIMARY KEY ("ext_cd"),
    CONSTRAINT "IX_orgaos_externos" UNIQUE ("ext_oet_cd", "ext_ds")
);

CREATE TABLE "lock_registro" (
    "usu_cd" integer NOT NULL,
    "den_cd" integer NOT NULL,
    "atd_cd" integer NOT NULL,
    "locktime" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "l_status" varchar(1) NOT NULL,
    "u_status" varchar(1) DEFAULT 'F' NOT NULL,
    CONSTRAINT "IX_lock_registro" UNIQUE ("den_cd", "atd_cd")
);

CREATE TABLE "vei_modelo" (
    "mod_cd" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "mar_cd" smallint NOT NULL,
    "mod_ds" varchar(30) NOT NULL,
    CONSTRAINT "PK_vei_modelo" PRIMARY KEY ("mod_cd", "mar_cd")
);

CREATE TABLE "xpto" (
    "xpt_cd" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "xpt_ds" varchar(40) NOT NULL,
    "xpt_st" smallint DEFAULT 0 NOT NULL,
    CONSTRAINT "PK_xpto" PRIMARY KEY ("xpt_cd"),
    CONSTRAINT "IX_xpto" UNIQUE ("xpt_ds")
);

CREATE TABLE "difusao_externa" (
    "dex_cd" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "dex_den_cd" integer NOT NULL,
    "dex_ext_cd" smallint NOT NULL,
    "dex_data" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "dex_dit_cd" smallint NOT NULL,
    "dex_usu_cd" smallint NOT NULL,
    CONSTRAINT "PK_difusao_externa" PRIMARY KEY ("dex_cd")
);

CREATE TABLE "classificacao" (
    "cld_cd" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "cld_ds" varchar(20) NOT NULL,
    "cld_st" smallint DEFAULT 0 NOT NULL,
    CONSTRAINT "PK_classificacao" PRIMARY KEY ("cld_cd"),
    CONSTRAINT "IX_classificacao" UNIQUE ("cld_ds")
);

-- Chaves estrangeiras
ALTER TABLE "assunto_denuncia" ADD CONSTRAINT "FK_assunto_denuncia_assunto_tipo" FOREIGN KEY ("ass_tpa_cd") REFERENCES "assunto_tipo" ("tpa_cd");
ALTER TABLE "assunto_tipo" ADD CONSTRAINT "FK_assunto_tipo_assunto_classe" FOREIGN KEY ("tpa_cla_cd") REFERENCES "assunto_classe" ("cla_cd");
ALTER TABLE "difusao_externa" ADD CONSTRAINT "FK_difusao_externa_orgaos_externos" FOREIGN KEY ("dex_ext_cd") REFERENCES "orgaos_externos" ("ext_cd");
ALTER TABLE "orgaos_externos" ADD CONSTRAINT "FK_orgaos_externos_orgaos_externos_tipos" FOREIGN KEY ("ext_oet_cd") REFERENCES "orgaos_externos_tipos" ("oet_cd");
ALTER TABLE "vei_modelo" ADD CONSTRAINT "FK_vei_modelo_vei_marca" FOREIGN KEY ("mar_cd") REFERENCES "vei_marca" ("mar_cd");
